language: cpp
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510-meta-minimal

script:
  # Link gcc-7 and g++-7 to their standard commands
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - source /opt/qt510/bin/qt510-env.sh
  - cd src
  - /opt/qt510/bin/qmake -project
  - /opt/qt510/bin/qmake bdsup2sub++.pro
  - make
  # Generate app image
  - if [ "$TRAVIS_OS_NAME" != "linux" ] ; then exit 0 ; fi
  - cd ..
  - mkdir dist
  - cp bundle/linux/* dist/
  - mv src/bdsup2sub++ dist/
  - chmod a+x tools/linuxdeployqt.AppImage
  - ./tools/linuxdeployqt.AppImage dist/bdsup2sub++ -appimage -bundle-non-qt-libs -verbose=2

deploy:
  provider: releases
  api-key:
    secure: ugNrU8zVluFmZfI26db09Tq4qGRDCcKjALlm5Y76Q+evTmQePKSJ4AVqzPz5TEzwuv0NVnbr7WYEMcBBglrSw1+HcXReaz33oAKZw9SVWm8XacjAU9TxHNvbtSOjDdd53o53fxxXHToaMe/m7NPJHnZBY6MAOeHUu/MNGYNniaVlpt8cE5NGJKd1KTytKMSGXmBKlPOJL/abkflFxNPs4DUXPf1JuRqVowU+RtprPtHKU0H1OrdjwCrdrfudwHPykIUDoW15JEqtdRqIQvvLfnwp+vjzK7JtOHIF3vdNcO4amDFUaDjPoZ7RAef/NHUgSG1km6srmYs0h08oTLuV1E6dANg3J/h3dlQV1WYte4H28g8hzjDhZZRPqYn2EvuQQWMo2LU7+e+e0inySLA32NRLhVZ4RdXDWvZCv/+yb3imNn4kB7nPvJnc1KP8l7bRXs7r4WEdGdMYhr5KlyhYq3iKM9CYfDwPLUx/P0+u8AlHgjsLcjftGkNZH7c9QTCNeIhtxJqlLruVerkexTX/VMkIteq70boCz8FqSyADnxIOoFfwfqnVJPNtPqD2iw7mktViGlKNz+Q0AjIU7BJCUNtb7iHirjjBvnqWiKEdhPWFOkuSHlaVKINO2HrQ8sMIYdspOMNuktpiRHvizVWg1COJ5uUF4IL5FFirql+ZSWs=
  file: BDSup2Sub++-x86_64.AppImage
  skip_cleanup: true
  on:
    repo: amichaeltm/BDSup2SubPlusPlus
    tags: true

