language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510-meta-minimal
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - source /opt/qt510/bin/qt510-env.sh
  - gcc --version
  - cd src
  - /opt/qt510/bin/qmake -project
  - /opt/qt510/bin/qmake bdsup2sub++.pro
  - make
