language: cpp
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510-meta-minimal

script:
  - source /opt/qt510/bin/qt510-env.sh
  - cd src
  - /opt/qt510/bin/qmake -project
  - /opt/qt510/bin/qmake bdsup2sub++.pro
  - make
